### ISSUE TITLE
Firewall RemoteAddress fails test if CIDR notation is used

### ISSUE THREAD

**Issue by globi84** [PowerShell/NetworkingDsc#404]
Hi

I use the NetworkingDSC Module in Version 7.2.0.0 and there is something wrong with RemoteAddress in CIDR format.

I use this configuration

```powershell
Firewall FPS-SMB-In-TCP-NoScope {
        Name          = 'FPS-SMB-In-TCP-NoScope'
        Ensure        = 'Present'
        Enabled       = 'True'
        Profile       = 'Domain'
        RemoteAddress = '192.168.1.0/24'
    }
```

after pushing to the client, the test is always false and give me this message

```
[[Firewall]FPS-RPCSS-In-TCP-NoScope::[FirewallSMB]SMB-Firewall-Config] Test-RuleProperties: RemoteAddress property value '192.168.1.0/255.255.255.0' does not match desired state '192.168.1.0/24'.
```

When I use '192.168.1.0/255.255.255.0' for the **remoteAddress** everything works fine

is there bug with the module or do I something wrong?

regards

christian

**Comment by PlagueHO** [comment]
Hi @globi84 - thanks for raising this. We are using the `New-NetFirewallRule` and `Set-NetFirewallRule` cmdlet to create the rules and these do support CIDR bit number of bits notation in the format you show: See https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps

But `Get-NetFirewallAddressFilter` always returns CIDR with subnet mask notation for the address filters no matter the input notation.
![image](https://user-images.githubusercontent.com/7589164/59136659-3b291480-89d8-11e9-8df4-58e8f788259f.png)

However, we actually have code to address this problem:
https://github.com/PowerShell/NetworkingDsc/blob/dev/DSCResources/MSFT_Firewall/MSFT_Firewall.psm1#L1204

But, there is a clear bug in it:

The above line:
```powershell
if ($parameter.Type -eq 'IPArray')
```

Should be:
```powershell
if ($parameter.Type -eq 'ArrayIP')
```

An easy fix but I'll improve the test automation as this shouldn't have got through.

Thanks again for raising this.

I think the easiest way to fix this would be to internally force a conversion from CIDR with number of bits to CIDR with subnet mask so that internally we're always comparing the same thing. The problem with that approach is that in the comparison verbose messages it might be misleading.

**Comment by globi84** [comment]
Hi PlagueHO

thanks for the fast response.

and the fast fix.

regards.
